!***************************************************************************
! m_typedef.f90
! -------------
! Copyright © 2007-2011, Eco2s team, Gerardo Fratini
! Copyright © 2011-2026, LI-COR Biosciences, Gerardo Fratini
! Copyright © 2026-    , ETH Zurich, Jonathan Muller
!
! This file is part of EddyFlow®.
!
! EddyFlow (TM) is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version. You should have received a copy
! of the GNU General Public License along with EddyFlow (R). If not,
! see <http://www.gnu.org/licenses/>.
!
! EddyFlow® contains additional Open Source Components. The licenses
! and/or notices these Components can be found in the file LIBRARIES.txt.
!
! EddyFlow® is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
! GNU General Public License for more details.
!
!***************************************************************************
!
! \brief       Module for definition of derived types
! \author      Gerardo Fratini
! \note
! \sa
! \bug
! \deprecated
! \test
! \todo
!***************************************************************************
module m_typedef
    use m_numeric_kinds
    use libdate
    implicit none
    save

    !> labels for array sizes
    integer, parameter :: MaxAvrgPeriodInHours = 5
    !> Total instruments. Anemometers and gas analysers share one counter in
    !> the .metadata file, so this is 8 devices, not 8 analysers. The tag
    !> tables that hold them are generated by prj/gen_metadata_tags.py - change
    !> this and re-run it, or the two will disagree.
    integer, parameter :: MaxNumInstruments = 8
    integer, parameter :: MaxNumRawFlags = 10
    integer, parameter :: NumDegH = 9
    !> Columns a .metadata file may describe. Sized from what a full-capacity
    !> project needs: 64 gases, 8 instruments x (4 cell + 2 diagnostic), the
    !> sonic and its diagnostic, air_t/air_p and MaxUserVar customs = 149.
    !> Must equal NUM_COLS in prj/gen_metadata_tags.py, which emits the
    !> per-column tag tables; the generator has a --check mode that says so.
    integer, parameter :: MaxNumCol = 200

    !> Gas capacity. A gas slot's species is decided at runtime from the
    !> project file, so this is a ceiling rather than a fixed list, and it is
    !> the *only* gas ceiling: nothing here limits how many of them one
    !> instrument may carry. A MaxGasesPerInstrument sat beside this and was
    !> never read - no array sized by it, no loop bounded by it - so it only
    !> ever described the interface's own input rule. Removed rather than left
    !> to be mistaken for a constraint the engine enforces.
    integer, parameter :: MaxNumGases = 64
    !> How many CO2/water pairs the partition may be run over, and how many
    !> further species each pair may carry. One pair per analyser is the shape
    !> this is sized for, so the ceiling is the instrument ceiling.
    integer, parameter :: MaxNumCecPairs = 8
    integer, parameter :: MaxNumCecExtra = 4

    !> Cell temperature in/out, cell pressure and average cell temperature, one
    !> set per instrument; diagnostics, two per instrument. Read by
    !> prj/gen_project_tags.py to size the record slots, so these are the single
    !> source of truth - change them and re-run it.
    integer, parameter :: MaxNumCellCols = MaxNumInstruments * 4
    integer, parameter :: MaxNumDiagCols = MaxNumInstruments * 2

    !> Cell measurements per instrument: cell_t, int_t_1, int_t_2, int_p.
    !> One set each, because a site with two analysers has two cells; a single
    !> set meant the second instrument's record silently overwrote the first.
    integer, parameter :: NumCellPerInstr = 4
    integer, parameter :: MaxNumCellSlots = MaxNumInstruments * NumCellPerInstr

    !> The anemometric block: u, v, w, ts. Named because three other constants
    !> and the whole variable enumeration below are offsets from it, and each
    !> used to spell it as a bare 4 or 5 that had to be kept in step by hand.
    integer, parameter :: NumAnemVar = 4

    !> u, v, w, ts + the gas slots + the per-instrument cell slots + air_t, air_p
    integer, parameter :: E2NumVar = NumAnemVar + MaxNumGases + MaxNumCellSlots + 2
    integer, parameter :: MaxNumDiag = 6
    !> Highest variable index, and therefore the width of every array indexed by
    !> variable: the anemometric block followed by the gas slots.
    !>
    !> NOT the gas count. Arrays declared (GHGNumVar) are addressed u..lastGas,
    !> so dropping the anemometric term would leave the four highest gas slots
    !> writing past the end of every one of them.
    integer, parameter :: GHGNumVar = NumAnemVar + MaxNumGases

    !> Width of the packed per-variable quality-flag strings: a leading filler
    !> digit followed by one digit per variable. These used to be built as
    !> base-10 integers (900000000 + sum(flag*10**(GHGNumVar-j))), which caps
    !> the variable count at ~9 before a 32-bit integer overflows. They are now
    !> built directly as characters, so the only limit is this length.
    integer, parameter :: FlagStrLen = 1 + GHGNumVar
    integer, parameter :: MaxUserVar = 30
    !> Per-analyser fields the dynamic metadata file can override, per gas:
    !> manufacturer, model, measure type, the three separations, the three
    !> tube properties, kw, ko, the two path lengths and tau. Spelled out in
    !> DynMDGasFieldNames.
    integer, parameter :: nDynMDGasFields = 14
    !> Widest row any of the readers below has to hold, in fields.
    !>
    !> The dynamic-metadata and calibration files carry per-gas fields, so
    !> their width scales with the gas count. The readers used literal 128
    !> and 256, which were ample when a project had four gases and are not
    !> now: nDynMDGasFields alone reaches 896 at MaxNumGases. Derived so a
    !> widened loop cannot leave a buffer behind, which is how
    !> raw_out_header came to overflow.
    integer, parameter :: MaxRowFields = &
        max(MaxNumCol, MaxNumGases * nDynMDGasFields + 64)
    !> Width of the raw-dataset header, in characters.
    !>
    !> ReadIniRP appends one 25-character name per selected variable, over the
    !> anemometric four, every gas slot and the cell and ambient columns - the
    !> E2 set, in other words - with a margin for the leading pad and any
    !> custom names. It was `character(512)`, which held four gases and was
    !> never widened when the loop that fills it became MaxNumGases.
    integer, parameter :: RawHeaderLen = 32 + 25 * (E2NumVar + 8)
    integer, parameter :: MaxNumBins = 300
    integer, parameter :: MaxNumBiometCol = 100
    !> Must track MaxNumInstruments, or instruments beyond this are silently
    !> absent from the essentials-file record.
    integer, parameter :: ExNumInstruments = 8

    integer, parameter :: DatumLen = 64
    integer, parameter :: CommLen = 1024
    integer, parameter :: PathLen = 1024
    integer, parameter :: FilenameLen = 256
    integer, parameter :: LongInstringLen = 8192
    integer, parameter :: ShortInstringLen = 1024
    !> Widest a header or a data row of the FLUXNET/essentials file may get.
    !>
    !> It has to hold the widest header the layout can produce, which is a
    !> per-gas block for up to sixty-four gases plus a Conditional Eddy
    !> Covariance block for up to eight pairings of up to six targets each.
    !> The CEC names are the long ones - CEC_TARGET_SLOT_6_<instrument>_2 - so
    !> that block alone can run to twenty thousand characters.
    !>
    !> A header longer than this is not reported: it is silently cut, and FCC
    !> then fails to find the NUM_BIOMET_VARS marker it locates the custom
    !> variables by. That is what a two-pairing project did against the old
    !> 16348, which is why the number is now well clear of any real layout
    !> rather than just clear of the one that was tried.
    integer, parameter :: LongOutstringLen = 65536

    integer, parameter :: iniLabelLen = 64
    integer, parameter :: iniValueLen = PathLen

    integer, parameter :: MaxGasClasses = 12
    integer, parameter :: toMaxH2OClass = 20
    integer, parameter :: MaxNumWSect = 36
    integer, parameter :: MaxNumWdfSectors = 16

    integer, parameter :: MaxProfNodes = 7
    integer, parameter :: NumStdCustom = 50


    !> labels for EddyFlow standard set
    integer, parameter :: u   = 1
    integer, parameter :: v   = 2
    integer, parameter :: w   = 3
    integer, parameter :: ts  = 4
    !> Bounds of the dynamic gas block. Species identity per slot comes from
    !> the project file at run time; use these to iterate over "all gases".
    !>
    !> Expressed from NumAnemVar so the gas block always starts immediately
    !> after ts, and lastGas is GHGNumVar by construction rather than by
    !> coincidence - the two were separately maintained literals before.
    integer, parameter :: firstGas = NumAnemVar + 1
    integer, parameter :: lastGas  = GHGNumVar
    !> The four gas slots EddyPro had, by position.
    !>
    !> They were co2, h2o, ch4, n2o and gas4 - names that read as species and
    !> meant positions, which is where every defect this migration fixed began.
    !> `E2Col(co2)` looks like "the carbon dioxide column" and is "the fifth
    !> variable", which is carbon dioxide only when a project happens to
    !> declare it first. Renaming them histGas1 and so on made each use honest
    !> but kept the species in the name; expressing them as offsets from
    !> firstGas removes it, and the count is what any of them ever meant.
    !>
    !> Four is the number EddyPro's format has, not a capacity: MaxNumGases
    !> is the capacity. These survive for the readers that accept the four
    !> historical spellings in files written before the records, and for the
    !> fallbacks used when a project describes no water or no CO2. The fixed
    !> output format and the three month-grouping tables that also needed them
    !> are both retired.
    !>
    !> Nothing that decides a number for a gas belongs here. Iterate
    !> firstGas..lastGas and resolve the species from its record.
    integer, parameter :: histGas1 = firstGas
    integer, parameter :: histGas2 = firstGas + 1
    integer, parameter :: histGas3 = firstGas + 2
    integer, parameter :: histGas4 = firstGas + 3
    !> Bounds of the per-instrument cell block. Instrument k (1-based) owns
    !> firstCell + (k-1)*NumCellPerInstr + {0,1,2,3}, in the order
    !> cell_t, int_t_1, int_t_2, int_p. Use CellSlot() rather than arithmetic
    !> at the call site.
    integer, parameter :: firstCell = lastGas + 1
    integer, parameter :: lastCell  = firstCell + MaxNumCellSlots - 1

    !> `moist_ref` value meaning "the biomet relative humidity", as opposed to
    !> a gas slot holding a hygrometer.
    !>
    !> Negative so it can never collide with a slot, and named so the eight
    !> places that read moist_ref can be found by grep. Every one of them
    !> bounds-checks against firstGas..lastGas, and each has to recognise this
    !> before that test - a sentinel that merely fails the bounds check would
    !> be indistinguishable from "nothing resolved", which is a different
    !> thing and, on a site with no biomet, the correct answer.
    integer, parameter :: biometMoistRef = -1

    !> The first instrument's cell slots keep their historical names, so code
    !> that predates per-instrument cells still addresses instrument 1.
    integer, parameter :: tc  = firstCell
    integer, parameter :: ti1 = firstCell + 1
    integer, parameter :: ti2 = firstCell + 2
    integer, parameter :: pi  = firstCell + 3
    integer, parameter :: pc  = firstCell + 3
    integer, parameter :: te  = lastCell + 1
    integer, parameter :: pe  = lastCell + 2

    !> The anemometer's slot in ExType%instr. There used to be four more -
    !> ico2, ih2o, ich4, igas4 - a second, five-wide numbering of the *same*
    !> analysers the gas slots already number, bridged by
    !> `igas = ico2 + (gas - co2)` in read_ex_record and mirrored across
    !> afterwards. Two numberings for one thing meant the ex record converted
    !> the first four analysers' units under one and the rest under a
    !> duplicate of that arithmetic, and it capped anything reached by role at
    !> four gases. Analysers are addressed by gas slot now, through
    !> ExType%gas_instr; the anemometer keeps this one because it is not a gas.
    integer, parameter :: sonic  = 1

    !> e2lab stood here: a per-slot label array whose first eight entries were
    !> 'u','v','w','ts','co2','h2o','ch4','n2o'. Nothing read it - not one
    !> reference in the tree outside its own declaration - and it was the last
    !> place a species name was pinned to a slot number by position. Column
    !> names come from GasOutputLabel and the tag helpers in
    !> gas_slot_resolution, which resolve the record, so a project ordering its
    !> gases differently gets its columns named for what it measured.

    !> labels for cospectra
    integer, parameter :: w_u   = 1
    integer, parameter :: w_v   = 2
    integer, parameter :: w_w   = 3
    integer, parameter :: w_ts  = 4
    !> The cospectral index space is the *same* space as u..lastGas - w_u = 1
    !> is u = 1 - so a cospectrum is addressed by the gas slot it belongs to,
    !> and these bounds are the gas bounds.
    !>
    !> w_co2, w_h2o, w_ch4 and w_gas4 used to sit here as a second set of names
    !> for slots five to eight. They were a duplicate of the gas slot constants
    !> in a different spelling, so a cospectrum could be addressed as w_h2o in
    !> one file and h2o in another and read as two different things. Nothing
    !> refers to them now.
    integer, parameter :: w_firstGas = firstGas
    integer, parameter :: w_lastGas  = lastGas

    !> Other labels
    integer, parameter :: fink_sims = 1
    integer, parameter :: mann_lens = 2
    integer, parameter :: lens      = 3

    type :: Numerical
        character(iniLabelLen) :: Label
        real(kind = dbl) :: Value
    end type Numerical

    type :: Text
        character(iniLabelLen) :: Label
        character(iniValueLen) :: Value
    end type Text

    type GenericE2Var
        real(kind = dbl) :: dbl(E2NumVar)
        integer :: int(E2NumVar)
        character(64) :: char(E2NumVar)
    end type GenericE2Var

    type :: AAType
        real(kind = dbl) :: min
        real(kind = dbl) :: max
        real(kind = dbl) :: lim
    end type AAType

    type :: ADCType
        character(32) :: Var
        character(32) :: VoltRange
        character(32) :: Constants
        character(32) :: Units
        character(32) :: PhysUnits
        real(kind = dbl) :: a
        real(kind = dbl) :: b
        real(kind = dbl) :: Vmin
        real(kind = dbl) :: Vmax
        real(kind = dbl) :: TLdef
        real(kind = dbl) :: TLmin
        real(kind = dbl) :: TLmax
    end type ADCType

    type :: ALType
        real(kind = dbl) :: u_max
        real(kind = dbl) :: w_max
        real(kind = dbl) :: t_min
        real(kind = dbl) :: t_max
        !> Per-gas plausibility bounds, indexed by gas slot (firstGas..lastGas).
        !> Were four named min/max pairs, one per legacy gas.
        real(kind = dbl) :: gas_min(GHGNumVar)
        real(kind = dbl) :: gas_max(GHGNumVar)
    end type ALType

   type :: AnemType
        character(20) :: Var
        character(20) :: Units
    end type AnemType

    type :: ARType
        integer :: lim
        integer :: bins
        real(kind = dbl) :: hf_lim
    end type ARType

    type :: LPTFType
        real(kind = dbl) :: dirga
        real(kind = dbl) :: dsonic
        real(kind = dbl) :: ba_sonic
        real(kind = dbl) :: ba_irga
        real(kind = dbl) :: zoh_sonic
        real(kind = dbl) :: m
        real(kind = dbl) :: wirga
        real(kind = dbl) :: wsonic
        real(kind = dbl) :: sver
        real(kind = dbl) :: shor
        real(kind = dbl) :: t
    end Type LPTFType

    type :: BPTFType
        real(kind = dbl) :: EXP(GHGNumVar)
        type(LPTFType)   :: LP(GHGNumVar)
        real(kind = dbl) :: HP(GHGNumVar)
        real(kind = dbl) :: BP(GHGNumVar)
    end type BPTFType

    type :: BinaryType
        integer :: head_nlines
        integer :: nbytes
        character(8) :: ascii_head_eol
        logical :: little_endian
    end type BinaryType

    type :: BiometFileMetadataType
        integer :: tsCols(7)
        integer :: numTsCol
        integer :: nhead
        integer :: time_step
        integer :: tolerance
        real(kind = dbl) :: duration
        character(1)     :: separator
        character(32)    :: tstamp_ref
        character(32)    :: tsPattern
        character(32)    :: data_label
        logical :: tsIso
    end type BiometFileMetadataType

    type :: BiometVarsType
        integer :: hpos
        integer :: vpos
        integer :: rep
        real(kind = dbl) :: gain
        real(kind = dbl) :: offset
        character(32) :: label
        character(32) :: pq_string
        character(32) :: fluxnet_label
        character(32) :: id
        character(32) :: base_name
        character(32) :: fluxnet_base_name
        character(32) :: accumul_type
        character(32) :: nature
        character(32) :: instr
        character(32) :: unit_in
        character(32) :: unit_out
        character(32) :: pretty_unit_out
        character(32) :: fluxnet_unit_out
    end type BiometVarsType

    type :: BiometColType
        character(32) :: var
        character(32) :: id
        character(32) :: instr
        character(32) :: unit_in
        character(32) :: unit_out
        real(kind = dbl) :: gain
        real(kind = dbl) :: offset
    end type BiometColType

    type :: BurbaParType
        real(kind = dbl) :: m(2, 3, 4)
        real(kind = dbl) :: l(2, 3, 2)
    end type BurbaParType

    type :: BurbaType
        real(kind = dbl) :: h_bot
        real(kind = dbl) :: h_top
        real(kind = dbl) :: h_spar
    end type BurbaType

    type :: CDSetupType
        integer :: ndir
        character(4) :: year
        character(10) :: start_date
        character(10) :: end_date
        logical :: filetype(20)
        logical :: recurse
        character(32) :: cstm(3)
    end type CDSetupType

    type :: CalibType
        character(10) :: date
        character(5)  :: time
        type(DateType) :: ts
        logical :: cleaning
        integer :: NumPeriods
        real(kind = dbl) :: offset(GHGNumVar)
        real(kind = dbl) :: ref(GHGNumVar)
        real(kind = dbl) :: ri(GHGNumVar)
        real(kind = dbl) :: rf(GHGNumVar)
        real(kind = dbl) :: Tcell
        real(kind = dbl) :: vmol
    end type CalibType

    type :: DriftCorrectionType
        character(32) :: method
        real(kind = dbl) :: dir_cal(0:6, GHGNumVar)
        real(kind = dbl) :: inv_cal(0:6, GHGNumVar)
        real(kind = dbl) :: b
        real(kind = dbl) :: c
    end type DriftCorrectionType

    type :: tsDriftsType
        type (DateType) :: Timestamp
        real (kind = dbl) :: offset(GHGNumVar)
    end type tsDriftsType

    type SwVerType
        integer :: major
        integer :: minor
        integer :: revision
    end type SwVerType

    type :: InstrumentType
        character(32) :: firm
        character(32) :: ep_label
        character(32) :: model
        character(32) :: category
        character(32) :: sw_ver_string
        real(kind = dbl) :: height
        real(kind = dbl) :: vpath_length
        real(kind = dbl) :: hpath_length
        real(kind = dbl) :: tau
        real(kind = dbl) :: north_offset
        real(kind = dbl) :: tube_l
        real(kind = dbl) :: tube_d
        real(kind = dbl) :: tube_f
        real(kind = dbl) :: hsep
        real(kind = dbl) :: nsep
        real(kind = dbl) :: esep
        real(kind = dbl) :: vsep
        real(kind = dbl) :: kw
        real(kind = dbl) :: ko
        !> The rate this instrument samples at [Hz], and whether it averages
        !> over that interval rather than reporting an instant.
        !>
        !> An instrument slower than the file's row rate leaves error rows
        !> between its samples - nineteen of every twenty for a 1 Hz analyser
        !> in a 20 Hz file - and every test that counted those against the
        !> whole period read the column as almost entirely missing and dropped
        !> it. `ac_freq <= 0` means "the file's rate", which is what every
        !> metadata file written before this says.
        real(kind = dbl) :: ac_freq
        logical :: integrates
        !> Which instr_<K>_* block of the .metadata this was read from.
        !>
        !> A column carries a COPY of its instrument, not a reference to it, so
        !> without this nothing downstream can say which instrument a column
        !> belongs to - and the project file keys its per-instrument settings
        !> by exactly that number. 0 is "no instrument matched", which falls
        !> back to the project-wide setting.
        integer :: slot
        character(32) :: wref
        character(32) :: wformat
        character(32) :: path_type
        character(32) :: measure_type
        logical :: head_corr
        logical :: master_sonic
        type(SwVerType) :: sw_ver
    end type InstrumentType

    type :: RawFlagType
        integer :: col
        real(kind = dbl) :: threshold
        logical :: upper
    end type RawFlagType

    type :: ColType
        character(32) :: var
        character(32) :: label
        character(32) :: measure_type
        character(32) :: instr_name
        character(32) :: unit_in
        character(32) :: conversion_type
        character(32) :: unit_out
        real(kind = dbl) :: min
        real(kind = dbl) :: max
        real(kind = dbl) :: a
        real(kind = dbl) :: b
        real(kind = dbl) :: def_tl
        real(kind = dbl) :: min_tl
        real(kind = dbl) :: max_tl
        real(kind = dbl) :: flag_thrshld
        !> What this column writes when it has no reading. `error` means the
        !> metadata declares nothing, which is every file written before the
        !> key existed - and needs to declare nothing, because -9999, NaN, an
        !> unparseable token and an empty field are recognised regardless.
        !> Only a logger writing something else has to say so.
        real(kind = dbl) :: err_value
        type (InstrumentType) :: instr
        type (RawFlagType) :: flag
        logical :: useit
        logical :: present
        real(kind = dbl) :: Va
        !> For gas slots: which E2Col slot supplies the H2O and the cell
        !> temperature/pressure used in this gas's calculations. Resolved from
        !> the project-file records after the E2 set is built; 0 means "not
        !> resolved", in which case the historical global h2o/tc/ti1/ti2/pi
        !> slots apply.
        integer :: moist_ref
        integer :: cell_ref
        !> The column's number in the .metadata file. Unused columns are
        !> dropped before the E2 set is built, so a column's position in
        !> LocCol/Raw is NOT its metadata number; anything that refers to a
        !> column by the number the project file stores must match on this.
        integer :: orig_col
    end type ColType

    type :: DegTType
        character(10) :: date
        character(5) :: time
        real(kind = dbl) :: zL
        real(kind = dbl) :: u
        real(kind = dbl) :: cov
        real(kind = dbl) :: dcov(9)
        logical :: def(9)
    end type DegTType

    type :: Diag7200Type
        logical :: present
        integer :: head_detect
        integer :: t_out
        integer :: t_in
        integer :: aux_in
        integer :: delta_p
        integer :: chopper
        integer :: detector
        integer :: pll
        integer :: sync
        real(kind = dbl) :: AGC
    end type Diag7200Type

    type :: Diag7500Type
        logical :: present
        integer :: chopper
        integer :: detector
        integer :: pll
        integer :: sync
        real(kind = dbl) :: AGC
    end type Diag7500Type

    type :: Diag7700Type
        logical :: present
        integer :: not_ready
        integer :: no_signal
        integer :: re_unlocked
        integer :: bad_temp
        integer :: laser_temp_unregulated
        integer :: block_temp_unregulated
        integer :: motor_spinning
        integer :: pump_on
        integer :: top_heater_on
        integer :: bottom_heater_on
        integer :: calibrating
        integer :: motor_failure
        integer :: bad_aux_tc1
        integer :: bad_aux_tc2
        integer :: bad_aux_tc3
        integer :: box_connected
    end type Diag7700Type

    type :: DiagAnemType
        logical :: binary_flag_present
        logical :: staa_present
    end type DiagAnemType

    type :: DirType
        character(PathLen) :: main_in
        character(PathLen) :: main_out
        character(PathLen) :: binned
        character(PathLen) :: full
        character(PathLen) :: biomet
    end type DirType

    type :: DOType
        real(kind = dbl) :: hf1_lim
        real(kind = dbl) :: hf2_lim
        real(kind = dbl) :: extlim_dw
        real(kind = dbl) :: extlim_up
    end type DOType

    type :: DSType
        real(kind = dbl) :: hf_uv
        real(kind = dbl) :: hf_w
        real(kind = dbl) :: hf_t
        !> Per-gas discontinuity limits, indexed by gas slot.
        real(kind = dbl) :: hf_gas(GHGNumVar)
        real(kind = dbl) :: hf_var
        real(kind = dbl) :: sf_uv
        real(kind = dbl) :: sf_w
        real(kind = dbl) :: sf_t
        real(kind = dbl) :: sf_gas(GHGNumVar)
        real(kind = dbl) :: sf_var
    end type DSType

    type :: MetadataType
        type(SwVerType) :: logger_swver
        integer :: ord(32)
        character(10) :: date
        character(5) :: time
        real(kind = dbl) :: alt
        real(kind = dbl) :: lat
        real(kind = dbl) :: lon
        real(kind = dbl) :: bar_press
        real(kind = dbl) :: canopy_height
        real(kind = dbl) :: d
        real(kind = dbl) :: z0
        real(kind = dbl) :: ac_freq
        real(kind = dbl) :: file_length
        character(256) :: sitename
        type(ColType) :: E2Col(E2NumVar)
    end type MetadataType

    type :: DynMDType
        character(32) :: measure_type(GHGNumVar)
        real(kind = dbl) :: alt
        real(kind = dbl) :: lat
        real(kind = dbl) :: lon
        real(kind = dbl) :: ac_freq
        real(kind = dbl) :: file_length
        real(kind = dbl) :: canopy_height
        real(kind = dbl) :: d
        real(kind = dbl) :: z0
        type(InstrumentType) :: Instr(E2NumVar)
    end type DynMDType

    !> Positions within a pair's target list. The pair's own water and carbon
    !> are always first and second, so a reader can name them without looking
    !> anything up; extra species follow in the order the pair states them.
    integer, parameter :: MaxNumCecTargets = 2 + MaxNumCecExtra
    integer, parameter :: cecTargetWater = 1
    integer, parameter :: cecTargetCarbon = 2

    !> One CO2/water pairing, as the project states it. Indices are into the
    !> gas records, 1-based, so they survive a project being re-ordered in a
    !> way raw column numbers would not.
    type :: CECPairType
        integer :: meth   !< 0 off, 1 water and carbon, 2 water only, 3 carbon only
        !> Named for the role, not the species: these are record indices and
        !> a bare `co2` reads as the retired slot constant of the same name.
        integer :: carbon !< gas record; 0 = the designated CO2
        integer :: water  !< gas record; 0 = the water on the carbon's analyser
        integer :: extra(MaxNumCecExtra)  !< further species to partition; 0 = unused
    end type CECPairType

    !> A pairing with its record indices resolved to gas slots, and the
    !> suffix its output columns carry. Resolution and naming come back from
    !> one call because the header and the rows are written by different
    !> executables: getting the list right and the naming wrong shifts the file
    !> exactly as getting the list wrong does.
    type :: CECResolvedPairType
        integer :: meth
        integer :: carbon_slot
        integer :: water_slot
        integer :: n_extra
        integer :: extra_slot(MaxNumCecExtra)
        character(48) :: tag
    end type CECResolvedPairType

    type :: CECSetupType
        real(kind = dbl) :: h            !< hyperbolic hole, in units of sigma_w*sigma_s
        real(kind = dbl) :: singular_band !< half-width of the r_Fc ~ -1 rejection band
        real(kind = dbl) :: min_o1_o2
        real(kind = dbl) :: min_octant
        real(kind = dbl) :: min_valid
        real(kind = dbl) :: signal_strength
        real(kind = dbl) :: max_stationarity
        integer :: stationarity_mode
        integer :: max_gap_fill
    end type CECSetupType

    !> once (one per instrument, or several on one instrument), so the species
    !> is data rather than a compile-time slot.
    type :: GasRecordType
        character(32) :: var        !< ASCII species slug: co2, h2o, ch4, cos...
        character(32) :: instr      !< canonical instrument id, or 'other'/'none'
        integer :: col              !< 1-based raw-file column; <=0 when unset
        integer :: moist            !< index into the gas records supplying H2O;
                                    !< 0 = auto (same instrument, else the first)
        integer :: cell             !< index into the cell records; 0 = auto
        real(kind = dbl) :: mw      !< molecular weight override; error = default
        real(kind = dbl) :: diff    !< diffusivity override; error = default
        integer :: fluxnet_default  !< 1 = this record carries the bare FLUXNET
                                    !< name for its species; 0 = numbered.
                                    !< Unset anywhere, the lowest record index
                                    !< of a species is designated.
    end type GasRecordType

    !> A cell temperature/pressure or diagnostic measurement, tied to the
    !> instrument that produced it.
    type :: MeasRecordType
        character(32) :: var
        character(32) :: instr
        integer :: col
    end type MeasRecordType

    type :: EddyFlowProjType
        integer :: sonic_output_rate
        integer :: col(E2NumVar + MaxNumDiag)
        real(kind=dbl) :: new_gas_diff
        character(10) :: start_date
        character(5)  :: start_time
        character(10) :: end_date
        character(5)  :: end_time
        character(32) :: title
        character(FilenameLen) :: id
        character(FilenameLen) :: fname_template
        character(32) :: ftype
        character(32) :: fext
        character(32) :: master_sonic
        character(32) :: lf_meth
        character(32) :: hf_meth
        character(32) :: err_label
        character(32) :: run_mode
        character(32) :: run_env
        character(32) :: caller
        character(32) :: biomet_data
        character(64) :: biomet_tail
        logical :: binned_spec_avail
        logical :: full_spec_avail
        logical :: biomet_dir
        logical :: biomet_recurse
        logical :: make_dataset
        logical :: subperiod
        logical :: wpl
        logical :: use_extmd_file
        logical :: use_dynmd_file
        logical :: out_full
        logical :: out_fluxnet
        logical :: fluxnet_standardize_biomet
        logical :: fluxnet_mode
        logical :: out_md
        logical :: out_avrg_cosp
        logical :: out_avrg_spec
        logical :: out_biomet
        logical :: fcc_follows
        logical :: hf_meth_in_situ
        logical :: hf_correct_ghg_ba
        logical :: hf_correct_ghg_zoh
        !> Master switch only. Which fluxes a given pairing partitions is the
        !> pairing's own business - a single project-wide 'water only' says
        !> nothing useful once there is more than one analyser.
        integer :: do_cec    !< 0 = disabled, 1 = enabled
        type(CECSetupType) :: cec
        !> Measurement records read from the project file. These are the only
        !> way a project names its gases, cell measurements and diagnostics.
        !>
        !> gas_num_stated separates two files that gas_num alone cannot:
        !> a project that says `gas_num=0` measures no gases and is perfectly
        !> valid - it still has wind and sonic temperature, so it still has a
        !> heat flux - while a project with no gas_num tag at all is a
        !> pre-5.0.0 file that never went through the interface, and is
        !> refused. Testing `gas_num <= 0` conflated the two and made an
        !> anemometer-only project unprocessable.
        logical :: gas_num_stated
        integer :: gas_num
        integer :: cell_num
        integer :: diag_num
        integer :: cec_num
        type(CECPairType) :: cec_pair(MaxNumCecPairs)
        type(GasRecordType)  :: gas(MaxNumGases)
        type(MeasRecordType) :: cell(MaxNumCellCols)
        type(MeasRecordType) :: diag(MaxNumDiagCols)
    end type EddyFlowProjType

    !> CEC component status values.
    integer, parameter :: cec_rejected = 0
    integer, parameter :: cec_normal = 1
    integer, parameter :: cec_all_stomatal = 2
    integer, parameter :: cec_all_nonstomatal = 3
    integer, parameter :: cec_singular = 4
    !> The authoritative total contradicts the octant statistics: the two
    !> components share a sign (r > 0), so the total must share it too. A
    !> negative ET would otherwise be split into a negative "transpiration".
    integer, parameter :: cec_wrong_sign = 5

    !> Which stationarity criterion gates the partition.
    !>
    !> Foken's statistic is |(GlbCov - AvrgCov) / GlbCov|, a RELATIVE measure
    !> whose denominator is the whole-period covariance - so it explodes
    !> whenever the flux is near zero, which at night it is, whether or not the
    !> period is genuinely non-stationary. It is a statement about the total
    !> covariance, and CEC does not use the total covariance: it uses the ratio
    !> of two conditional ones, which is far more robust to a drift because a
    !> trend contaminates both octants alike and largely cancels.
    !>
    !> cec_stat_flux is what Zahn et al. did and stays the default. cec_stat_
    !> ratio applies the same construction to the quantity the method actually
    !> uses. Either way cec_max_stationarity is the threshold, and 0 disables
    !> the gate entirely.
    integer, parameter :: cec_stat_flux = 0
    integer, parameter :: cec_stat_ratio = 1

    !> One scalar partitioned in one pair's octants.
    !>
    !> The octants are NOT recomputed per target. Zahn et al. (Sec. 2.4) define
    !> the indicator functions on (w', q', c') alone and say they "remain the
    !> same" for the second scalar - which is the whole reason a species the
    !> octants know nothing about, carbonyl sulfide among them, can be
    !> partitioned by the same pass that partitions water and carbon.
    type :: CECTargetType
        integer :: slot                 !< gas slot; 0 = unused
        real(kind = dbl) :: f_O1        !< (1/N) sum over O1 of w's'
        real(kind = dbl) :: f_O2        !< (1/N) sum over O2 of w's'
        real(kind = dbl) :: r           !< f_O1 / f_O2
        !> Foken's stationarity construction applied to r rather than to the
        !> total covariance, in percent. error when fewer than three
        !> sub-intervals could produce a ratio. Reported whatever the gate is
        !> set to, so the two criteria can be compared on the same run.
        real(kind = dbl) :: ns_r
        integer :: status
        logical :: valid
    end type CECTargetType

    !> High-frequency Conditional Eddy Covariance partition descriptor, for one
    !> CO2/water pair. Everything here comes from the raw series alone, which is
    !> what lets RP compute it and FCC apply it to its own corrected totals.
    type :: CECDescriptorType
        integer :: meth
        integer :: carbon_slot
        integer :: water_slot
        integer :: n_target
        integer :: n_valid
        integer :: n_O1
        integer :: n_O2
        real(kind = dbl) :: frac_O1
        real(kind = dbl) :: frac_O2
        type(CECTargetType) :: target(MaxNumCecTargets)
    end type CECDescriptorType

    !> One partitioned scalar's two components and the total they sum to. The
    !> status is the flux's own, not the descriptor's: whether the partition
    !> holds also depends on the authoritative total, which the descriptor has
    !> never seen.
    type :: CECComponentType
        real(kind = dbl) :: nonstomatal  !< the O1 component: E, Reco, soil COS
        real(kind = dbl) :: stomatal     !< the O2 component: T,  P,   plant COS
        real(kind = dbl) :: total        !< what this pair partitioned
        integer :: status
    end type CECComponentType

    !> Results of Conditional Eddy Covariance partitioning (Zahn et al. 2022),
    !> for one pair. Every scalar is in its own gas's flux units; the two depth
    !> equivalents are the water target expressed in mm hour-1.
    type :: CECFluxType
        type(CECComponentType) :: comp(MaxNumCecTargets)
        real(kind = dbl) :: E_cec_ET
        real(kind = dbl) :: Tr_cec_ET
    end type CECFluxType

    type :: EddyFlowLogType
        logical :: save_native
        logical :: timestamp
        logical :: enable_proc
        logical :: iso_format
        logical :: tstamp_end
        character(30) :: native_format
    end type EddyFlowLogType

    type :: SASetupType
        integer :: min_smpl
        integer :: foken_lim
        integer :: nclass(E2NumVar)
        integer :: class(E2NumVar, 12)
        real(kind = dbl) :: fmin(E2NumVar)
        real(kind = dbl) :: fmax(E2NumVar)
        real(kind = dbl) :: hfn_fmin(GHGNumVar)
        real(kind = dbl) :: min_un_ustar
        real(kind = dbl) :: min_un_H
        real(kind = dbl) :: min_un_LE
        !> Per-gas spectral-assessment thresholds, indexed by gas slot.
        !> h2o is not here: its counterpart is the LE threshold above.
        real(kind = dbl) :: min_un_gas(GHGNumVar)
        real(kind = dbl) :: min_st_ustar
        real(kind = dbl) :: min_st_H
        real(kind = dbl) :: min_st_LE
        real(kind = dbl) :: min_st_gas(GHGNumVar)
        real(kind = dbl) :: max_ustar
        real(kind = dbl) :: max_H
        real(kind = dbl) :: max_LE
        real(kind = dbl) :: max_gas(GHGNumVar)
        character(32) :: lptf
        character(32) :: cosp
        character(32) :: cosp_type
        character(32) :: horst_lens09
        character(10) :: start_date
        character(10) :: end_date
        character(5) :: start_time
        character(5) :: end_time
        logical :: filter_cosp_by_vm_flags
        logical :: add_sonic_lptf
        logical :: automatic_config
        logical :: ibrom_model
        logical :: in_situ
        logical :: subperiod
    end type SASetupType

    type :: FCCsetupType
        character(10)  :: start_date
        character(5)   :: start_time
        character(10)  :: end_date
        character(5)   :: end_time
        character(32)  :: H_corr
        logical :: keep_parent
        logical :: do_spectral_assessment
        logical :: pass_thru_spectral_assessment
        logical :: import_full_cospectra
        type(SASetupType) :: SA
    end type FCCsetupType

    type :: FCCMetadataType
        character(32)    :: H2oPathType
        !> The same, per gas slot. H2oPathType is the primary hygrometer's, and
        !> the RH/cut-off fit needs each hygrometer's own: an open path is
        !> fitted analytically and a closed one by least squares, and on a site
        !> with one of each the second was fitted by whichever arm the first
        !> happened to take.
        character(32)    :: GasPathType(GHGNumVar)
        !> The rate each analyser samples at, as RP resolved it. FCC has no
        !> metadata file, so this comes off the ex record; a record written
        !> before that column existed leaves it at the error code and every
        !> reader falls back to ac_freq, the station's own rate.
        real(kind = dbl) :: GasAcFreq(GHGNumVar)
        real(kind = dbl) :: ac_freq
        logical          :: ru
    end type FCCMetadataType

    type :: FileListType
        character(FilenameLen) :: name
        character(PathLen) :: path
        type(DateType)  :: timestamp
    end type FileListType

    type :: FileType
        character(PathLen) :: tlag_opt
        character(PathLen) :: metadata
        character(PathLen) :: DynMD
        character(PathLen) :: biomet
        character(PathLen) :: ex
        character(PathLen) :: pf
        character(PathLen) :: to
        character(PathLen) :: sa
    end type FileType

    !> One configured gas measurement. Replaces the fixed col_co2/col_h2o/
    !> col_ch4/col_gas4 slots: a site can describe the same species more than
    type :: FluxType
        character(10) :: date
        character(5) :: time
        !> Per-gas fluxes, indexed by E2Col slot. Were four named scalars
        !> (co2/h2o/ch4/gas4); a project can now configure more gases than
        !> that, so the flux of gas N has to be addressable by N.
        !> `E`/`LE`/`ET`/`H` and the stability below stay scalar as the
        !> *designated* hygrometer's values - the ones carrying the bare
        !> FLUXNET column names. Every hygrometer's own set is in the `_at`
        !> arrays, indexed by that hygrometer's E2Col slot.
        real(kind = dbl) :: gas(GHGNumVar)
        real(kind = dbl) :: E
        real(kind = dbl) :: ET
        !> Evapotranspiration evaluated at each gas's own time lag, and the
        !> internal sensible heat term for each gas. `E_gas(h2o)` is unused -
        !> the H2O counterpart is `E` above.
        real(kind = dbl) :: E_gas(GHGNumVar)
        real(kind = dbl) :: LE
        real(kind = dbl) :: H
        real(kind = dbl) :: Hi_gas(GHGNumVar)
        real(kind = dbl) :: tau
        real(kind = dbl) :: ustar
        real(kind = dbl) :: L
        real(kind = dbl) :: zL
        !> One set per hygrometer, indexed by its own E2Col slot.
        !>
        !> A site with two hygrometers has two humidities, and every quantity
        !> derived from humidity has two values. Reporting one of them and
        !> discarding the other is a choice the data does not support: the
        !> second hygrometer produced a water flux and nothing else - no latent
        !> heat, no evapotranspiration, no sensible heat of its own, no
        !> stability - so there was no way to see the two disagree.
        !>
        !> `tau` is here and `ustar` is not, which is the opposite way round
        !> from how it first reads. u* comes from the wind covariances alone
        !> (Flux0%ustar = Ambient%us) and carries no humidity; tau is
        !> rho_a * u*^2 and carries it through rho_a. A per-hygrometer u*
        !> column would be a copy of the one beside it - worse than absent,
        !> because a reader would take the agreement for corroboration.
        !>
        !> The designated hygrometer's entry and the scalar above are the same
        !> number by construction - the scalar is assigned from the entry, not
        !> computed alongside it - so the bare columns cannot drift from the
        !> numbered one that describes the same instrument.
        real(kind = dbl) :: E_at(GHGNumVar)
        real(kind = dbl) :: LE_at(GHGNumVar)
        real(kind = dbl) :: ET_at(GHGNumVar)
        real(kind = dbl) :: H_at(GHGNumVar)
        real(kind = dbl) :: tau_at(GHGNumVar)
        real(kind = dbl) :: L_at(GHGNumVar)
        real(kind = dbl) :: zL_at(GHGNumVar)
    end type FluxType

    type :: FileCheckType
        logical :: first
        logical :: second
    end type FileCheckType

    type :: FileInterpreterType
        integer :: header_rows
        integer :: ulongs
        character(1) :: separator
        character(64) :: data_label
        character(8)  :: tob1_format
        logical :: discard_if_above
        logical :: file_with_text
    end type FileInterpreterType

    type :: FootType
        real(kind = dbl) :: peak
        real(kind = dbl) :: offset
        real(kind = dbl) :: x10
        real(kind = dbl) :: x30
        real(kind = dbl) :: x50
        real(kind = dbl) :: x70
        real(kind = dbl) :: x80
        real(kind = dbl) :: x90
    end type FootType

    type FPCheckType
        integer :: outliers
    end type FPCheckType

    type FPFlagType
        logical :: outliers
    end type FPFlagType

    !> H2OCovType held water covariances at three named gases' time lags -
    !> tl_co2, tl_ch4, tl_gas4 - and was never declared, passed or read
    !> anywhere. The quantity it described is carried per slot by
    !> FluxType%E_gas(GHGNumVar), which reaches every gas.

    type HeaderType
        character(64) :: var
        character(64) :: units
    end type HeaderType

    type :: EssentialsType
        character(FilenameLen) :: fname
        integer :: e2spikes(E2NumVar)
        integer :: m_custom_flags
        integer :: m_wdf
        integer :: m_despiking(E2NumVar)
        integer :: m_diag_anem
        integer :: m_diag_irga(E2NumVar)
        integer :: n_in
        integer :: n_after_custom_flags
        integer :: n_after_wdf
        integer :: n_wcov(E2NumVar)
        integer :: n(E2NumVar)
        integer :: ZCD(GHGNumVar)
        integer :: al_s(GHGNumVar)
        real(kind = dbl) :: yaw
        real(kind = dbl) :: pitch
        real(kind = dbl) :: roll
        real(kind = dbl) :: ustar
        real(kind = dbl) :: zL
        real(kind = dbl) :: L
        real(kind = dbl) :: degH(NumDegH + 1)
        real(kind = dbl) :: used_timelag(E2NumVar)
        real(kind = dbl) :: actual_timelag(E2NumVar)
        real(kind = dbl) :: AGC72
        real(kind = dbl) :: AGC75
        real(kind = dbl) :: RSSI77
        real(kind = dbl) :: LGD(GHGNumVar)
        real(kind = dbl) :: KID(GHGNumVar)
        real(kind = dbl) :: CorrDiff(GHGNumVar, GHGNumVar)
        real(kind = dbl) :: mahrt98_NR(GHGNumVar)
        real(kind = dbl) :: rand_uncer(E2NumVar)
        real(kind = dbl) :: rand_uncer_LE
        real(kind = dbl) :: rand_uncer_ET
        real(kind = dbl) :: ar_s(GHGNumVar)
        real(kind = dbl) :: do_s_ctr(GHGNumVar)
        real(kind = dbl) :: do_s_ext(GHGNumVar)
        real(kind = dbl) :: sk_s_skw(GHGNumVar)
        real(kind = dbl) :: sk_s_kur(GHGNumVar)
        real(kind = dbl) :: ds_s_haar_avg(6, GHGNumVar)
        real(kind = dbl) :: ds_s_haar_var(6, GHGNumVar)
        real(kind = dbl) :: aa_s
        real(kind = dbl) :: ns_s_rnv(2)
        real(kind = dbl) :: ns_s_rns
        logical :: def_tlag(E2NumVar)
    end type EssentialsType

    type :: LongSpectraType
        real(kind = dbl) :: fn(GHGNumVar)
        real(kind = dbl) :: of(GHGNumVar)
        real(kind = dbl) :: ts(GHGNumVar)
    end type LongSpectraType

    !> Only the biomet column selection survives. The profile heights - zT and
    !> one array per gas, plus the five-row dz built from them - were read
    !> from the project and consumed by nothing: their only reader was the
    !> profile-storage block in storage.f90, commented out for as long as the
    !> fork has existed.
    !>
    !> They are not widened to N gases, because a fixed dz(5, ...) is the
    !> shape of the feature rather than an oversight in it. If profile storage
    !> is revived it wants a height per gas record, which is a different type.
    type :: BiometSetupType
        integer :: sel(6)
    end type BiometSetupType

    type :: SpecMethType
        integer :: nbins
        character(32) :: lp_meth
        character(32) :: lptf
        character(32) :: cosp
        character(32) :: cosp_type
        logical :: hptf
        logical :: add_sonic_lptf
    end type SpecMethType

    type :: BiometMeasType
        real(kind = dbl) :: val
        character(32) :: label
        character(32) :: id
        character(32) :: sensor
        character(32) :: units
        character(32) :: integration_type
        type(DateType) :: timestamp
    end type BiometMeasType

    type :: BiometType
        real(kind = dbl) :: val(6)
        logical :: Pused
        logical :: RHused
        logical :: Tused
    end type BiometType

    type :: Mul7700Type
        real(kind = dbl) :: A
        real(kind = dbl) :: B
        real(kind = dbl) :: C
    end type Mul7700Type

    type :: MethType
        character(8)  :: det
        character(32) :: rot
        character(32) :: tlag
        character(32) :: wpl
        character(32) :: qcflag
        character(32) :: foot
        character(32) :: Hcorr
        type(SpecMethType) :: spec
    end type MethType

    type :: MFSetupType
        character(30) :: met_ext
        character(30) :: separator
        character(30) :: policy
        character(30) :: logger
        character(30) :: out_fname
        character(30) :: mtype
        character(30) :: dproto
        character(30) :: tproto
        logical :: tstamp_end
    end type MFSetupType

    type :: ModelParType
        real(kind = dbl) :: Wd
        real(kind = dbl) :: U
        real(kind = dbl) :: Us
        real(kind = dbl) :: L
    end type ModelParType

    type :: NSType
        real(kind = dbl) :: hf_lim
    end type NSType

    type :: AmbientStateType
        real(kind = dbl) :: VPD
        real(kind = dbl) :: Va
        real(kind = dbl) :: Vd
        real(kind = dbl) :: Ta
        real(kind = dbl) :: Td
        real(kind = dbl) :: Tmap
        real(kind = dbl) :: Tcell
        real(kind = dbl) :: Pcell
        real(kind = dbl) :: Ts
        real(kind = dbl) :: Q
        real(kind = dbl) :: lambda
        real(kind = dbl) :: bowen
        real(kind = dbl) :: sigma
        !> Water-to-dry-air density ratio per H2O measurement, indexed by that
        !> measurement's E2Col slot. `sigma` above remains the single-H2O
        !> value; per-gas WPL uses sigma_at(moisture slot) instead.
        real(kind = dbl) :: sigma_at(GHGNumVar)
        !> The biomet humidity expressed the way a hygrometer's channel is.
        !>
        !> These used to be written straight into Stats%chi/r/d of the primary
        !> hygrometer, so that instrument's reported concentration was the
        !> biomet value and its own measurement was lost. They are their own
        !> quantity now, reported as h2o_biomet_*, and a hygrometer reports
        !> what it measured. A gas that names the biomet as its moisture
        !> source is corrected from these.
        !>
        !> Ambient-based throughout, including the molar density - unlike the
        !> overwrite they replace, which divided by the primary analyser's cell
        !> volume. A site humidity has no cell.
        real(kind = dbl) :: chi_biomet
        real(kind = dbl) :: r_biomet
        real(kind = dbl) :: d_biomet
        !> The rest of the moisture regime, per hygrometer, on the same index.
        !> Each is the scalar above replayed from one hygrometer's own vapour
        !> density: a second hygrometer reads a different humidity, so it
        !> implies a different dry-air partial pressure and therefore its own
        !> air density, specific humidity and heat capacity. H, LE, ET and the
        !> stability derived from them are computed once per entry.
        !>
        !> Air temperature is deliberately NOT here. Ta comes from the sonic
        !> corrected for humidity, so a per-hygrometer Ta would give the site
        !> two air temperatures and, through molar volume and every WPL term,
        !> two values for every gas flux. These are all computed from the one
        !> settled Ta, which is what keeps the widening bounded.
        real(kind = dbl) :: e_at(GHGNumVar)
        real(kind = dbl) :: RH_at(GHGNumVar)
        real(kind = dbl) :: rho_d_at(GHGNumVar)
        real(kind = dbl) :: rho_a_at(GHGNumVar)
        real(kind = dbl) :: Q_at(GHGNumVar)
        real(kind = dbl) :: RhoCp_at(GHGNumVar)
        !> Cell temperature and pressure of the analyser measuring each gas,
        !> indexed by that gas's E2Col slot. The scalars above stay as the
        !> first instrument's values, which is what a single-analyser site has
        !> always used and what the rest of the code still reads.
        real(kind = dbl) :: Tcell_at(GHGNumVar)
        real(kind = dbl) :: Pcell_at(GHGNumVar)
        real(kind = dbl) :: e
        real(kind = dbl) :: es
        real(kind = dbl) :: p_d
        real(kind = dbl) :: RhoCp
        real(kind = dbl) :: WS
        real(kind = dbl) :: MWS
        real(kind = dbl) :: us
        real(kind = dbl) :: L
        real(kind = dbl) :: zL
        real(kind = dbl) :: alpha
    end type AmbientStateType

   type :: PFSetupType
        integer :: num_sec
        integer :: min_per_sec
        integer :: avrg_len
        integer :: wsect_end(MaxNumWSect)
        real(kind = dbl) :: width(MaxNumWSect)
        real(kind = dbl) :: w_max
        real(kind = dbl) :: u_min
        real(kind = dbl) :: north_offset
        real(kind = dbl) :: max_lack
        character(4) :: year
        character(10) :: start_date
        character(10) :: end_date
        character(5) :: start_time
        character(5) :: end_time
        character(32) :: fix
        logical :: subperiod
        logical :: wsect_exclude(MaxNumWSect)
    end type PFSetupType

   type :: RUsetupType
        integer :: tlag_max
        character(32) :: meth
        character(32) :: its_meth
    end type RUsetupType

    type :: RPsetupType
        integer :: tcell_filter_tconst
        integer :: Tconst
        integer :: nspec
        integer :: avrg_len
        integer :: wdf_num_secs
        integer  :: covmax_var
        real(kind = dbl) :: wdf_start(MaxNumWdfSectors)
        real(kind = dbl) :: wdf_end(MaxNumWdfSectors)
        real(kind = dbl) :: offset(3)
        !> How much of the file's own data may be missing, in percent - the
        !> anemometer's allowance and the whole period's, both measured on the
        !> row grid.
        real(kind = dbl) :: max_lack
        !> The same, per instrument, measured against what THAT instrument
        !> should have produced at its own rate. `error` means the project says
        !> nothing about this instrument, which is every project written before
        !> the key existed, and resolves back to max_lack.
        real(kind = dbl) :: instr_max_lack(MaxNumInstruments)
        character(32) :: tap_win
        character(32) :: bu_corr
        character(32) :: calib_aoa
        logical :: apply_wdf
        logical :: calib_wboost
        logical :: do_spectral_analysis
        logical :: use_geo_north
        logical :: power_of_two
        logical :: bu_multi
        logical :: filter_al
        logical :: filter_sr
        logical :: filter_by_raw_flags
        logical :: calib_cw
        logical :: despike
        logical :: pf_onthefly
        logical :: to_onthefly
        logical :: pf_assessment_only
        logical :: tlag_assessment_only
        logical :: pf_subtract_b0
        logical :: recurse
        logical :: despike_vickers97
        logical :: out_biomet
        logical :: out_qc_details
        logical :: out_bin_sp
        logical :: out_bin_og
        logical :: out_full_sp(GHGNumVar)
        logical :: out_full_cosp(GHGNumVar)
        logical :: out_raw_var(E2NumVar)
        logical :: out_st(7)
        logical :: out_raw(7)
        logical :: covmax_stocdet
    end type RPsetupType

    type :: PrType
        real(kind = dbl) :: d
        real(kind = dbl) :: a
        real(kind = dbl) :: w
        real(kind = dbl) :: ws
        real(kind = dbl) :: VPD
    end type PrType

    type :: QCType
        integer :: w_u
        integer :: w_ts
        !> Per-gas quality quantities, indexed by gas slot (firstGas..lastGas).
        !> Were four named members apiece, which is why the Foken flags and the
        !> steady-state statistics stopped at the fourth gas.
        integer :: w_gas(GHGNumVar)
        integer :: u
        integer :: w
        integer :: ts
        integer :: tau
        integer :: gas(GHGNumVar)
        integer :: H
        character(32) :: Filename
        character(10) :: date
        character(5) :: time
    end type QCType

    type :: RegParType
        real(kind = dbl) :: Fn
        real(kind = dbl) :: fc
        real(kind = dbl) :: f2
        real(kind = dbl) :: e1
        real(kind = dbl) :: e2
        real(kind = dbl) :: e3
    end type RegParType

    type :: MassParType
        real(kind = dbl) :: a0
        real(kind = dbl) :: fpeak
        real(kind = dbl) :: mu
    end type MassParType

    type :: RotType
        real(kind = dbl) :: yaw
        real(kind = dbl) :: pitch
        real(kind = dbl) :: roll
        logical :: D3
    end type RotType

    type :: RHOType
        real(kind = dbl) :: d
        real(kind = dbl) :: a
        real(kind = dbl) :: w
        !> Water vapour mass density computed from each H2O measurement,
        !> indexed by that measurement's E2Col slot. `w` above stays the
        !> single-H2O value so the many existing references keep working;
        !> gases resolve through their own moisture reference instead.
        real(kind = dbl) :: w_at(GHGNumVar)
    end type RHOType

    type :: RSCharFlagType
        character(FlagStrLen) :: sr
        character(FlagStrLen) :: ar
        character(FlagStrLen) :: do
        character(FlagStrLen) :: al
        character(FlagStrLen) :: sk
        character(FlagStrLen) :: ds
        character(FlagStrLen) :: tl
        character(FlagStrLen) :: aa
        character(FlagStrLen) :: ns
    end type RSCharFlagType

    !> Only the whole-run outcomes are still integers. The per-variable tests
    !> pack their flags directly as strings, because the base-10 encoding
    !> caps the variable count at about nine before a 32-bit integer
    !> overflows; sr, ar, do, al, sk and ds went first and tl last. Leaving
    !> their members here would let a future test pick the packing that
    !> bounded TestTimeLag at four gases.
    type :: RSIntFlagType
        integer :: aa
        integer :: ns
    end type RSIntFlagType

    type :: ScalarType
        logical :: IsMixRatio
        logical :: IsMolFraction
        logical :: IsMolDensity
    end type ScalarType

    type :: SiteType
        real(kind = dbl) :: Alt
        real(kind = dbl) :: Lat
        real(kind = dbl) :: BarPr
        real(kind = dbl) :: canopy_height
        real(kind = dbl) :: d
        real(kind = dbl) :: z0
    end type SiteType

    type :: SKType
        real(kind = dbl) :: hf_skmin
        real(kind = dbl) :: hf_skmax
        real(kind = dbl) :: hf_kumin
        real(kind = dbl) :: hf_kumax
        real(kind = dbl) :: sf_skmin
        real(kind = dbl) :: sf_skmax
        real(kind = dbl) :: sf_kumin
        real(kind = dbl) :: sf_kumax
    end type SKType

    type :: SpectralType
        real(kind = dbl) :: of(GHGNumVar)
    end type SpectralType

    type :: SpectraSetType
        integer :: fnum
        real(kind = dbl) :: fn
        real(kind = dbl) :: fnorm
        real(kind = dbl) :: of(GHGNumVar)
    end type SpectraSetType

    type :: FitSpectraType
        real(kind = dbl) :: fnorm(GHGNumVar)
        real(kind = dbl) :: of(GHGNumVar)
    end type FitSpectraType

    type :: MeanSpectraType
        integer :: cnt(GHGNumVar)
        integer :: fnum(GHGNumVar)
        real(kind = dbl) :: fn(GHGNumVar)
        real(kind = dbl) :: of(GHGNumVar)
        real(kind = dbl) :: ts(GHGNumVar)
    end type MeanSpectraType

    type :: SRType
        integer :: num_spk
        real(kind = dbl) :: lim_u
        real(kind = dbl) :: lim_w
        !> Per-gas spike limit, indexed by gas slot (firstGas..lastGas).
        !> Was four named scalars, one per legacy gas; a project can now
        !> describe the same species more than once, so the limit has to
        !> follow the slot rather than the species name.
        real(kind = dbl) :: lim_gas(GHGNumVar)
        real(kind = dbl) :: hf_lim
    end type SRType

    type :: StationType
        real(kind = dbl) :: AcFreq
        real(kind = dbl) :: FileLength
        real(kind = dbl) :: hm
        real(kind = dbl) :: HorSep
        real(kind = dbl) :: VerSep
    end type StationType

    type :: StatsType
        real(kind = dbl) :: TKE
        real(kind = dbl) :: wind_dir
        real(kind = dbl) :: wind_dir_stdev
        real(kind = dbl) :: Mean(E2NumVar)
        real(kind = dbl) :: Cov(E2NumVar, E2NumVar)
        real(kind = dbl) :: StDev(E2NumVar)
        real(kind = dbl) :: Skw(E2NumVar)
        real(kind = dbl) :: Kur(E2NumVar)
        real(kind = dbl) :: Median(E2NumVar)
        real(kind = dbl) :: Q3(E2NumVar)
        real(kind = dbl) :: Q1(E2NumVar)
        real(kind = dbl) :: d(E2NumVar)
        real(kind = dbl) :: chi(E2NumVar)
        real(kind = dbl) :: r(E2NumVar)
        !> Water and cell-temperature covariances taken at *another* gas's
        !> timelag, indexed by that gas's slot. Seven named scalars before -
        !> h2ocov_tl_co2/ch4/gas4 and tc_cov_tl_co2/h2o/ch4/gas4 - which named
        !> a position rather than a species and stopped at the fourth, so a
        !> fifth gas got no internal sensible heat flux and no timelag-matched
        !> evapotranspiration however it was configured. The water entry is
        !> absent from h2ocov_tl by construction: water's covariance with
        !> itself at its own lag is Cov(w, wsl).
        real(kind = dbl) :: h2ocov_tl(E2NumVar)
        real(kind = dbl) :: tc_cov_tl(E2NumVar)
        real(kind = dbl) :: T
        real(kind = dbl) :: Pr
        real(kind = dbl) :: RH
        logical :: daytime
        integer :: nlines
        character(32) :: Filename
        character(10) :: start_date
        character(10) :: date
        ! character(10) :: mdate
        character(5) :: start_time
        character(5) :: time
        ! character(5) :: mtime
    end type StatsType

    type :: UserStatsType
        real(kind = dbl) :: Mean(MaxUserVar)
        real(kind = dbl) :: Cov(MaxUserVar, MaxUserVar)
        real(kind = dbl) :: StDev(MaxUserVar)
        real(kind = dbl) :: Skw(MaxUserVar)
        real(kind = dbl) :: Kur(MaxUserVar)
        character(10) :: date
        character(5) :: time
    end type UserStatsType

    type :: StorType
        real(kind = dbl) :: H
        real(kind = dbl) :: LE
        real(kind = dbl) :: ET
        real(kind = dbl) :: of(GHGNumVar)
    end type StorType

    type :: TestType
        logical :: sr
        logical :: ar
        logical :: do
        logical :: al
        logical :: sk
        logical :: ds
        logical :: tl
        logical :: aa
        logical :: ns
    end type TestType

    type :: TimeLagType
        real(kind = dbl) :: def
        real(kind = dbl) :: min
        real(kind = dbl) :: max
    end type TimeLagType

    type :: TimeLagDatasetType
        real(kind = dbl) :: tlag(E2NumVar)
        !> The relative humidity of the period that produced tlag(slot), per
        !> slot. It was one scalar per row against a per-slot tlag, and the
        !> dataset is compacted per slot - each gas has its own count of
        !> valid determinations - so with two hygrometers the RH at row k and
        !> the lag at row k came from different half-hours.
        real(kind = dbl) :: RH(E2NumVar)
    end type TimeLagDatasetType

    type :: TimeLagOptType
        real(kind = dbl) :: Tlag(E2NumVar)
        real(kind = dbl) :: T
        real(kind = dbl) :: RH
    end type TimeLagOptType

    type :: TOSetupType
        integer :: h2o_nclass
        real(kind = dbl) :: h2o_class_size
        !> Minimum flux for a period to enter the time-lag optimisation
        !> dataset, indexed by gas slot. h2o is excluded: its counterpart is
        !> the RH-class machinery above.
        real(kind = dbl) :: gas_min_flux(GHGNumVar)
        real(kind = dbl) :: le_min_flux
        real(kind = dbl) :: pg_range
        real(kind = dbl) :: min_lag(GHGNumVar)
        real(kind = dbl) :: max_lag(GHGNumVar)
        character(10) :: start_date
        character(10) :: end_date
        character(5) :: start_time
        character(5) :: end_time
        logical :: subperiod
    end type TOSetupType

    type :: PWBSetupType
        real(kind = dbl) :: min_lag(GHGNumVar)
        real(kind = dbl) :: max_lag(GHGNumVar)
        logical :: lag_bounds_provided(GHGNumVar)
        integer :: n_bootstrap
        real(kind = dbl) :: block_length_s
        real(kind = dbl) :: min_valid_frac
        real(kind = dbl) :: hdi_thresh_s
        real(kind = dbl) :: dev_thresh_s
        real(kind = dbl) :: hdi_prefilter_s
        integer :: smoothing_width
        integer :: random_seed
        !> Furthest a lag may travel to a period that detected none, in hours
        !> of elapsed time; 0 is unlimited, which is the paper's behaviour.
        !> It bounds interpolation, forward carry and backward fill alike -
        !> bounding one direction only would achieve nothing, since with
        !> detections either side of a long unusable stretch the later one
        !> would fill from the future exactly the span the earlier one was
        !> just forbidden to cross.
        !>
        !> dyco counts averaging periods here. This counts hours, because our
        !> table has a row only where a period was processed: across a week of
        !> missing raw files a period count measures rows present rather than
        !> time passed, and would quietly reach across the outage.
        real(kind = dbl) :: max_carry_h
    end type PWBSetupType

    type :: PWBResultType
        real(kind = dbl) :: selected_lag
        integer :: row_lag
        real(kind = dbl) :: applied_lag
        integer :: applied_row_lag
        real(kind = dbl) :: hdi_low
        real(kind = dbl) :: hdi_high
        real(kind = dbl) :: hdi_range
        character(24) :: reliability_class
        character(2) :: best_combination
        character(24) :: fallback_source
        !> Wide enough for a record-derived species tag; a truncated label
        !> would not round-trip through GasIndexFromLabel.
        character(32) :: donor_gas
        integer :: origin_gas
        logical :: edge_pinned
        logical :: fallback_used
        logical :: block_length_clamped
        real(kind = dbl) :: effective_min_lag
        real(kind = dbl) :: effective_max_lag
        real(kind = dbl) :: effective_block_length_s
        real(kind = dbl) :: raw_covariance
        real(kind = dbl) :: ccf_at_mode
        !> How this period's lag was arrived at: 'native', 'instrument_shared',
        !> 'interpolated', 'backfilled', 'median', 'nominal', 'maxcov_default'.
        !> Distinct from reliability_class, which says how good the detection
        !> was; this says which arm of the gap-filling produced the number.
        character(24) :: fill_method
        !> The peak the detector saw over the evaluated range, which extends a
        !> guard band beyond the declared window. The applied lag is always the
        !> restricted one; this is what says whether the window was well chosen.
        real(kind = dbl) :: unrestricted_peak_lag
        logical :: peak_outside_window
        !> Discarded by the HDI pre-filter before S1/S2 ran.
        logical :: hdi_prefiltered
        !> Hours the settled lag travelled to reach this period: 0 where it
        !> was detected here, the elapsed distance where it was carried,
        !> interpolated or filled backward.
        real(kind = dbl) :: carry_hours
        !> The deterministic pre-whitening diagnostics. tlag_pw is the peak of
        !> the unsmoothed full-data pre-whitened CCF (R: tl_pww) and corr_pw
        !> its value there (R: cor_pww); cv_99 is R's Bartlett 99% band, so a
        !> |corr_pw| below it means the pre-whitened correlation is not
        !> distinguishable from noise however narrow the bootstrap HDI is.
        real(kind = dbl) :: tlag_pw
        real(kind = dbl) :: corr_pw
        real(kind = dbl) :: cv_99
        logical :: differenced
        integer :: ar_order_scalar
        integer :: ar_order_w
        integer :: ar_order_t
    end type PWBResultType

    !> One PWB result as persisted in a per-period time-lag cache.
    type :: PWBTimelagCacheEntryType
        character(10) :: date
        character(5) :: time
        integer :: gas
        real(kind = dbl) :: actual_lag
        real(kind = dbl) :: used_lag
        integer :: row_lag
        logical :: default_used
        type(PWBResultType) :: result
    end type PWBTimelagCacheEntryType

    type :: TLType
        !> Nominal time lag per gas, indexed by gas slot.
        real(kind = dbl) :: def_gas(GHGNumVar)
        real(kind = dbl) :: hf_lim
        real(kind = dbl) :: sf_lim
    end type TLType

    type :: TubeType
        real(kind = dbl) :: l
        real(kind = dbl) :: d
        real(kind = dbl) :: f
    end type TubeType

    type :: WPLType
        real(kind = dbl) :: dilut
        real(kind = dbl) :: exp
        real(kind = dbl) :: burba
    end type WPLType

    type ExType
        character(FilenameLen) :: fname
        character(12) :: start_timestamp
        character(12) :: end_timestamp
        character(10) :: start_date
        character(10) :: end_date
        character(5) :: start_time
        character(5) :: end_time
        !> VM97 outcomes, transposed: one string per test, one digit per
        !> variable. The two packings of these flags are easy to confuse and
        !> only this one is gas-bounded. In the file a field is per *variable*
        !> and 9 characters wide (a filler plus the 8 tests), which no gas count
        !> changes. Here the array index is the test and the string position is
        !> the variable, so the width must cover u,v,w,ts plus every gas slot -
        !> which is exactly FlagStrLen. At character(9) a fifth gas had nowhere
        !> to go and its outcome was written over the end of the string.
        character(FlagStrLen) :: vm_flags(8)
        !> The time-lag pair carries one digit per *gas* behind a leading
        !> filler, so it grows with the gas count exactly as vm_flags does.
        !> These were character(9) because the test that filled them packed
        !> four digits into a base-10 integer; at eight gases the cell is nine
        !> characters and at any more it was silently truncated on the way
        !> through the ex file.
        !>
        !> aoa and nshw stay at 9: they are single-digit whole-run outcomes,
        !> not per-variable strings.
        character(FlagStrLen) :: vm_tlag_hf
        character(FlagStrLen) :: vm_tlag_sf
        character(9) :: vm_aoa_hf
        character(9) :: vm_nshw_hf
        character(32) :: measure_type(GHGNumVar)
        character(8) :: det_meth
        integer :: file_records
        integer :: used_records
        integer :: spikes(GHGNumVar)
        integer :: det_meth_int
        integer :: measure_type_int(GHGNumVar)
        integer :: nr_theor
        integer :: nr_files
        integer :: nr_after_custom_flags
        integer :: nr_after_wdf
        integer :: nr(GHGNumVar)
        integer :: nr_w(GHGNumVar)
        integer :: nighttime_int
        integer :: ncustom
        real(kind = dbl) :: DOY_start
        real(kind = dbl) :: DOY_end
        real(kind = dbl) :: RP
        real(kind = dbl) :: file_length
        real(kind = dbl) :: lat
        real(kind = dbl) :: lon
        real(kind = dbl) :: alt
        real(kind = dbl) :: licor_flags(29)
        real(kind = dbl) :: det_timec
        real(kind = dbl) :: unrot_u
        real(kind = dbl) :: unrot_v
        real(kind = dbl) :: unrot_w
        real(kind = dbl) :: rot_u
        real(kind = dbl) :: rot_v
        real(kind = dbl) :: rot_w
        real(kind = dbl) :: MWS
        real(kind = dbl) :: WS
        real(kind = dbl) :: WD
        real(kind = dbl) :: WD_SIGMA
        real(kind = dbl) :: ustar
        real(kind = dbl) :: TKE
        real(kind = dbl) :: L
        real(kind = dbl) :: zL
        real(kind = dbl) :: Bowen
        real(kind = dbl) :: Tstar
        real(kind = dbl) :: d(GHGNumVar)
        real(kind = dbl) :: r(GHGNumVar)
        real(kind = dbl) :: chi(GHGNumVar)
        real(kind = dbl) :: Ts
        real(kind = dbl) :: Ta
        real(kind = dbl) :: Pa
        real(kind = dbl) :: RH
        real(kind = dbl) :: Va
        real(kind = dbl) :: RhoCp
        real(kind = dbl) :: Cp
        real(kind = dbl) :: e
        real(kind = dbl) :: es
        real(kind = dbl) :: Q
        real(kind = dbl) :: VPD
        real(kind = dbl) :: Tdew
        !> The biomet humidity as a concentration, carried so FCC can put
        !> it in the full output beside each hygrometer's own reading.
        real(kind = dbl) :: chi_biomet
        real(kind = dbl) :: r_biomet
        real(kind = dbl) :: d_biomet
        real(kind = dbl) :: Pd
        real(kind = dbl) :: Vd
        real(kind = dbl) :: lambda
        real(kind = dbl) :: sigma
        !> Water vapour terms of the H2O measurement that corrects each gas,
        !> indexed by that gas's own E2Col slot. RP resolves the per-gas
        !> moisture reference and writes these out; FCC recomputes the fluxes
        !> from the ex file and would otherwise see only the single global
        !> `sigma` / `RHO%w` above. Left at `error` where unresolved, in which
        !> case the global values apply.
        real(kind = dbl) :: rhow_at(GHGNumVar)
        real(kind = dbl) :: sigma_at(GHGNumVar)
        !> The rest of that H2O's regime, on the same index and written by the
        !> same block. Two terms were enough while the only per-gas quantity
        !> was the WPL dilution; a per-hygrometer sensible heat flux needs the
        !> air its hygrometer implies - specific humidity, wet air density,
        !> heat capacity - and the spectral corrections need its humidity.
        !>
        !> A hygrometer's own moisture reference is itself, so the entry
        !> indexed by an H2O slot is that hygrometer's own regime. That is what
        !> makes this block, keyed by gas, also the carrier for the
        !> per-hygrometer quantities: no second block to keep in step.
        real(kind = dbl) :: q_at(GHGNumVar)
        real(kind = dbl) :: rhoa_at(GHGNumVar)
        real(kind = dbl) :: rhocp_at(GHGNumVar)
        real(kind = dbl) :: rh_at(GHGNumVar)
        !> Gas slots the ex file actually carried terms for, in file order.
        !> FCC rewrites the row and must replay exactly this set: deriving it
        !> again from the values would drop any gas whose terms happened to be
        !> error for that averaging period, leaving the row a field short of
        !> the header.
        integer :: n_gas_moist
        integer :: gas_moist_slot(GHGNumVar)
        !> Which rule supplied each gas's PWB timelag. Read rather than
        !> discarded so FCC can echo it: FCC rewrites every row, and dropping
        !> these four columns shifted everything after them out of step with
        !> the header.
        real(kind = dbl) :: pwb_source(GHGNumVar)
        !> Analyser describing each gas, indexed by the gas's own E2Col slot.
        !> `instr` above is indexed by instrument role (sonic, ico2 .. igas4)
        !> and so only reaches four gases; past that the role index addresses
        !> an unrelated instrument. Flux code should read this instead.
        type(InstrumentType) :: gas_instr(GHGNumVar)
        integer :: n_gas_instr
        integer :: gas_instr_slot(GHGNumVar)
        !> Instrument 1's cell conditions, in the units the FLUXNET row
        !> declares them in - degC and kPa. Kept for the columns that report
        !> them; not usable in the physics, which needs K and Pa.
        real(kind = dbl) :: Tcell
        real(kind = dbl) :: Pcell
        real(kind = dbl) :: Vcell(GHGNumVar)
        !> Cell conditions of the analyser that measured each gas, in SI and
        !> read back unchanged. The scalars above pass through the writer's
        !> degC/kPa gains and the reader does not invert them, so FCC's WPL
        !> was dividing by a cell temperature in degC and a pressure in kPa.
        real(kind = dbl) :: Tcell_at(GHGNumVar)
        real(kind = dbl) :: Pcell_at(GHGNumVar)
        !> Covariance of w with that analyser's own cell pressure.
        real(kind = dbl) :: cov_w_pcell(GHGNumVar)
        real(kind = dbl) :: Var(E2NumVar)
        real(kind = dbl) :: Cov_w(E2NumVar)
        real(kind = dbl) :: tlag(GHGNumVar)
        real(kind = dbl) :: act_tlag(GHGNumVar)
        real(kind = dbl) :: used_tlag(GHGNumVar)
        real(kind = dbl) :: nom_tlag(GHGNumVar)
        real(kind = dbl) :: min_tlag(GHGNumVar)
        real(kind = dbl) :: max_tlag(GHGNumVar)
        real(kind = dbl) :: yaw
        real(kind = dbl) :: pitch
        real(kind = dbl) :: roll
        real(kind = dbl) :: TAU_SS
        real(kind = dbl) :: H_SS
        !> Steady-state statistic per gas flux, indexed by gas slot. Was
        !> FC_SS/FH2O_SS/FCH4_SS/FGS4_SS - four named scalars, so the ex file
        !> could carry the statistic for only the first four gases.
        real(kind = dbl) :: F_SS(GHGNumVar)
        real(kind = dbl) :: U_ITC
        real(kind = dbl) :: W_ITC
        real(kind = dbl) :: TS_ITC
        real(kind = dbl) :: avrg_length
        real(kind = dbl) :: ac_freq
        real(kind = dbl) :: canopy_height
        real(kind = dbl) :: disp_height
        real(kind = dbl) :: rough_length
        real(kind = dbl) :: agc72
        real(kind = dbl) :: agc75
        real(kind = dbl) :: rssi77
        real(kind = dbl) :: user_var(MaxUserVar)
        real(kind = dbl) :: rand_uncer(E2NumVar)
        real(kind = dbl) :: rand_uncer_LE
        real(kind = dbl) :: rand_uncer_ET
        logical :: not_enough_data
        logical :: daytime
        logical :: var_present(GHGNumVar)
        logical :: def_tlag(GHGNumVar)
        type(StorType) :: Stor
        type(RhoType) :: RHO
        type(Mul7700Type) :: Mul7700
        type(BurbaType) :: Burba
        type(DegTType) :: degT
        type(InstrumentType) :: instr(ExNumInstruments)
        type(FluxType) :: Flux0
        Type(SwVerType) :: logger_swver
        type(StatsType) :: stats
        integer :: n_cec
        type(CECDescriptorType) :: cec(MaxNumCecPairs)
    end type ExType

    type fluxnetChunksType
        character(LongOutstringLen) s(6)
    end type fluxnetChunksType

contains

    character(32) function InstrumentModelBase(model)
        implicit none
        !> in/out variables
        character(*), intent(in) :: model
        !> local variables
        integer :: model_len

        InstrumentModelBase = 'none'
        model_len = len_trim(model)
        if (model_len > 2) InstrumentModelBase = model(1:model_len - 2)
    end function InstrumentModelBase

    !***************************************************************************
    !> Current key for an instrument model, whatever spelling the file uses.
    !>
    !> The Campbell keys were renamed: EddyPro's bare `csat3` and `csat3b` are
    !> `csi_csat3` and `csi_csat3b` now. No other manufacturer moved - every
    !> Gill, Metek, Young and LI-COR key is what EddyPro wrote - so this only
    !> ever fires on a Campbell site. Left unmapped the model matches nothing
    !> in the select cases downstream and metadata validation rejects the file,
    !> which for a GHG archive means every file in the run is skipped.
    !>
    !> The interface additionally tolerates the manufacturer-name prefix that
    !> one release wrote. It is deliberately absent here: that prefix is a
    !> retired identifier in this program and a static check bans the string
    !> outright, so a file spelling it that way is an interface-side concern.
    !>
    !> Only the key is rewritten. The value carries a trailing `_<n>` pairing it
    !> with an instrument, and every reader strips it with the same
    !> two-character arithmetic InstrumentModelBase uses, so the suffix has to
    !> come back untouched.
    !***************************************************************************
    character(32) function CanonicalInstrumentModel(model)
        implicit none
        !> in/out variables
        character(*), intent(in) :: model
        !> local variables
        character(32) :: base
        integer :: model_len

        CanonicalInstrumentModel = model
        model_len = len_trim(model)
        if (model_len <= 2) return

        base = InstrumentModelBase(model)
        !> No bare 'csat3c', 'ec155' or 'tga200a': those arrived already
        !> carrying a prefix, so no file can spell them this way.
        select case (trim(base))
            case ('csat3');  base = 'csi_csat3'
            case ('csat3a'); base = 'csi_csat3a'
            case ('csat3b'); base = 'csi_csat3b'
            case ('ec150');  base = 'csi_ec150'
            case default;    return
        end select

        CanonicalInstrumentModel = trim(base) // model(model_len - 1:model_len)
    end function CanonicalInstrumentModel

    logical function IsOpenPathIrgaModel(model)
        implicit none
        !> in/out variables
        character(*), intent(in) :: model

        select case (InstrumentModelBase(model))
            case ('li7700', 'li7500', 'li7500a', 'li7500rs', 'li7500ds', &
                'generic_open_path', 'open_path_krypton', 'open_path_lyman', &
                'csi_ec150', 'csi_irgason_irga')
                IsOpenPathIrgaModel = .true.
            case default
                IsOpenPathIrgaModel = .false.
        end select
    end function IsOpenPathIrgaModel

    logical function IsClosedPathIrgaModel(model)
        implicit none
        !> in/out variables
        character(*), intent(in) :: model

        select case (InstrumentModelBase(model))
            case ('li7200', 'li7200rs', 'li6262', 'li7000', &
                'generic_closed_path', 'closed_path_krypton', 'closed_path_lyman', &
                'csi_ec155', 'csi_tga200a', &
                'miro_mga1_5', 'miro_mga4_6', 'miro_mga9_10', 'miro_mgai_n2o', &
                'aerodyne_tildas')
                IsClosedPathIrgaModel = .true.
            case default
                IsClosedPathIrgaModel = .false.
        end select
    end function IsClosedPathIrgaModel

    character(32) function IrgaPathTypeFromModel(model)
        implicit none
        !> in/out variables
        character(*), intent(in) :: model

        if (IsOpenPathIrgaModel(model)) then
            IrgaPathTypeFromModel = 'open'
        elseif (IsClosedPathIrgaModel(model)) then
            IrgaPathTypeFromModel = 'closed'
        else
            IrgaPathTypeFromModel = 'none'
        end if
    end function IrgaPathTypeFromModel
end module m_typedef
